/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox;

import org.junit.Test;
import static org.junit.Assert.*;

public class LoxTest {
    @Test public void testAppHasAGreeting() {
        Lox classUnderTest = new Lox();
//        assertNotNull("app should have a greeting", );
    }
}
